### ISSUE TITLE
Cannot require module

### ISSUE THREAD

**Issue by teddav** [davideast/Querybase#22]
Hi,
I added Querybase to my package.json and installed it. Even removed node_modules and reinstalled everything but it seems like I can't import Querybase.
I get the error: **Error: Cannot find module 'querybase'**

**Comment by davideast** [comment]
Can you show what you have tried?

**Comment by teddav** [comment]
Show? Don't know what you mean exactly.

I have my package.json with my dependencies:
"dependencies": {
    "express": "^4.14.0",
    "firebase": "^3.2.1",
    "querybase": "^0.3.0"
  }
Ran **npm install**
Then in my index.js: **require("querybase")**

And that is it. When i run with **node index.js** I get the error and it crashes

**Comment by teddav** [comment]
Hi David,
Still no idea what's wrong?

**Comment by davideast** [comment]
Fixed thanks to @jsayol!

**Comment by teddav** [comment]
Great, thanks!
Tried to update to the new version, but seems to be stuck on 0.3.0. How can i update?

**Comment by jsayol** [comment]
I don't think David has published a new version yet. If you really need to get it now you could edit your package.json to use the git repo instead of the published npm package.

Open `package.json` and under the `dependencies` section changes this:

    "querybase": "^0.3.0"

To this:

    "querybase": "davideast/Querybase"

And then just `npm install`. Be careful when using git repos as dependencies, though, and Keep an eye out for the new version on npm to change it back whenever it's published.

**Comment by davideast** [comment]
@jsayol You are correct! I was trying to sneak in some other changes, but I have not had the time. I'll do a release today.
