### ISSUE TITLE
What makes this experimental?

### ISSUE THREAD

**Issue by soumak77** [davideast/Querybase#26]
I'm looking to use this project in production and was wondering what exactly makes this project experimental?  Are there technical reasons to avoid using this project or is it just a matter of support/liability?

**Comment by davideast** [comment]
Great question!

If you used this library in production, you'd be the first one to do so. That's pretty much the definition of an experiment.

The more technical reasons are that automatic composite indexing within the record itself brings bloat on the download. I wrote this library to illustrate the idea of composite keying. In reality you want to index on the fields you find valuable, rather than just every combination.

Also support is a big deal. This is a side project for and I try to do updates once a month or so on it, which is hardly the SLA you're looking for.

The more I wrote this library the more I realized too that I want to change the direction. Rather than store the composite keys with each record, I could break them out into their own index tree and then use Rxjs to merge each listener as if it were a child listener event.

Feel free to try it in any demo projects or just take the ideals of composite keys and apply it to your own app. Composite keying is great for enhancing Firebase querying.

**So the tl;dr;** is this project is a not only an experiment for it's durability and support, but for it's overall usage and direction. I'm thinking something great can come of it, but we can only find out by trying and making mistakes.

**Comment by soumak77** [comment]
Thanks for the feedback!  After reviewing the project I do agree that one should roll their own logic based on their needs if they wish to use it in production.  I am already do something similar in my project, so using Querybase won't add much benefit on top of that.

One major feature which I was hoping to see when I first stumbled across this project was the ability to perform multiple where statements with comparisons.  For example `a > 3 && b > 10`.  Is there any way to perform that type of query without client-side filtering or use of another database?

Although Querybase doesn't appear to support it, I believe you could use composite keys to achieve multiple where statements, so long as there is only one non-equal comparison.  For instance, the following queries could be run `a == 3 && b > 10` or `a == 3 && b == 10 && c > 4`.

**Comment by quadsurf** [comment]
@davideast querybase is a godsend... any chance it will ever be officially adopted by Google's Firebase?

**Comment by soumak77** [comment]
I ended up writing [Firebase Reporting](https://github.com/soumak77/firebase-reporting) to suit my needs.  Firebase Reporting provides an easy way to generate and retrieve metrics on data being stored in firebase.

I would like to integrate the features of Querybase into Firebase Reporting using the method @davideast suggested:
> Rather than store the composite keys with each record, I could break them out into their own index tree and then use Rxjs to merge each listener as if it were a child listener event.

Firebase Reporting stores the report metrics in an isolated tree, so it should be possible to integrate the method above.
