### ISSUE TITLE
Firebase keeps warning for missing indexes

### ISSUE THREAD

**Issue by beebase** [davideast/Querybase#33]
Why does firebase keeps warning me about indexes I already defined?
![image](https://cloud.githubusercontent.com/assets/446089/19806313/61693c72-9d1a-11e6-85ec-562ed6d6c261.png)

![image](https://cloud.githubusercontent.com/assets/446089/19806335/875daeea-9d1a-11e6-9814-bf1fe2595d9d.png)

**Comment by jsayol** [comment]
Querybase requires you to define special indexes. Notice the difference between `.indexOn`, which you have, and `._indexOn`, which Querybase is asking you to define. Just switch your Querybase indexes (those starting with "querybase~~") to the latter and the warning should go away.

**Comment by beebase** [comment]
Thanks. I already tried that, but Firebase gave me a syntax error .
I'll have another look today and post back.

**Comment by jsayol** [comment]
You're right, it seems like the console won't allow to use arrays on anything other than `.indexOn`.

**Comment by davideast** [comment]
@beebase @jsayol That's an error in the message. There should be no `_` in `indexOn`. As for the multiple warnings, that's Querybase, not Firebase. I have no idea of knowing when you've specified indexes, and since the indexes are generated by Querybase, I log to the console what you should specify for the indexes. 

I'm going to be extremely busy of the next week, but if someone is up for fixing this easy bug I'd gladly accept the PR! [It's a simple one char change right here](https://github.com/davideast/Querybase/blob/master/src/querybase.ts#L633).

**Comment by jsayol** [comment]
@davideast my bad, I assumed otherwise just by reading the message. PR created.

See you in Berlin, I'm sure all the hard work will pay off :)

**Comment by davideast** [comment]
Closed due to @jsayol's great PR! #36
