### ISSUE TITLE
Not Null Statement

### ISSUE THREAD

**Issue by TonGarcia** [davideast/Querybase#42]
Hey, how can I query by: "not null attribute"?
orderBy.starts(!null) works on angularfire. is it working in this framework?

**Comment by davideast** [comment]
@TonGarcia Can you show your AngularFire code that works?

**Comment by TonGarcia** [comment]
@davideast it is not an open source project, but the code is bellow:

```javascript
var query = carsArrayRef.orderByChild('lt').startAt(!null).endAt(!null);
```

**Comment by davideast** [comment]
@TonGarcia That is not actually a NOT NULL statement. The `!null` translates to `false` in JavaScript. Your query ends up being:

```js
var query = carsArrayRef.orderByChild('lt').startAt(false).endAt(false);
```

The `endAt(false)` doesn't do anything for you since the `startAt` value is also `false`.

I'm closing because this is not a query the Firebase Database supports.
[
Check something like this SO post for more details.](http://stackoverflow.com/questions/39086203/firebase-query-exclude-data-where-a-specific-field-is-null)
